// Code generated by protoc-gen-go. DO NOT EDIT.
// source: node.proto

package node

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NewNodeRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	IsBootstrap          bool     `protobuf:"varint,2,opt,name=isBootstrap,proto3" json:"isBootstrap,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewNodeRequest) Reset()         { *m = NewNodeRequest{} }
func (m *NewNodeRequest) String() string { return proto.CompactTextString(m) }
func (*NewNodeRequest) ProtoMessage()    {}
func (*NewNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{0}
}

func (m *NewNodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewNodeRequest.Unmarshal(m, b)
}
func (m *NewNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewNodeRequest.Marshal(b, m, deterministic)
}
func (m *NewNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewNodeRequest.Merge(m, src)
}
func (m *NewNodeRequest) XXX_Size() int {
	return xxx_messageInfo_NewNodeRequest.Size(m)
}
func (m *NewNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewNodeRequest proto.InternalMessageInfo

func (m *NewNodeRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *NewNodeRequest) GetIsBootstrap() bool {
	if m != nil {
		return m.IsBootstrap
	}
	return false
}

type StartListenerRequest struct {
	Port                 uint32   `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartListenerRequest) Reset()         { *m = StartListenerRequest{} }
func (m *StartListenerRequest) String() string { return proto.CompactTextString(m) }
func (*StartListenerRequest) ProtoMessage()    {}
func (*StartListenerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{1}
}

func (m *StartListenerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartListenerRequest.Unmarshal(m, b)
}
func (m *StartListenerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartListenerRequest.Marshal(b, m, deterministic)
}
func (m *StartListenerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartListenerRequest.Merge(m, src)
}
func (m *StartListenerRequest) XXX_Size() int {
	return xxx_messageInfo_StartListenerRequest.Size(m)
}
func (m *StartListenerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartListenerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartListenerRequest proto.InternalMessageInfo

func (m *StartListenerRequest) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type MemoryRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MemoryRequest) Reset()         { *m = MemoryRequest{} }
func (m *MemoryRequest) String() string { return proto.CompactTextString(m) }
func (*MemoryRequest) ProtoMessage()    {}
func (*MemoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{2}
}

func (m *MemoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemoryRequest.Unmarshal(m, b)
}
func (m *MemoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemoryRequest.Marshal(b, m, deterministic)
}
func (m *MemoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemoryRequest.Merge(m, src)
}
func (m *MemoryRequest) XXX_Size() int {
	return xxx_messageInfo_MemoryRequest.Size(m)
}
func (m *MemoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MemoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MemoryRequest proto.InternalMessageInfo

func (m *MemoryRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type GeneralResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GeneralResponse) Reset()         { *m = GeneralResponse{} }
func (m *GeneralResponse) String() string { return proto.CompactTextString(m) }
func (*GeneralResponse) ProtoMessage()    {}
func (*GeneralResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{3}
}

func (m *GeneralResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeneralResponse.Unmarshal(m, b)
}
func (m *GeneralResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeneralResponse.Marshal(b, m, deterministic)
}
func (m *GeneralResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeneralResponse.Merge(m, src)
}
func (m *GeneralResponse) XXX_Size() int {
	return xxx_messageInfo_GeneralResponse.Size(m)
}
func (m *GeneralResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GeneralResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GeneralResponse proto.InternalMessageInfo

func (m *GeneralResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*NewNodeRequest)(nil), "node.NewNodeRequest")
	proto.RegisterType((*StartListenerRequest)(nil), "node.StartListenerRequest")
	proto.RegisterType((*MemoryRequest)(nil), "node.MemoryRequest")
	proto.RegisterType((*GeneralResponse)(nil), "node.GeneralResponse")
}

func init() { proto.RegisterFile("node.proto", fileDescriptor_0c843d59d2d938e7) }

var fileDescriptor_0c843d59d2d938e7 = []byte{
	// 259 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x4d, 0x09, 0x56, 0x47, 0x52, 0x61, 0xad, 0x10, 0x7a, 0x0a, 0xf1, 0x52, 0x14, 0x7a,
	0xd0, 0x8b, 0x17, 0x3d, 0x88, 0xe8, 0xa5, 0xf6, 0xb0, 0x0a, 0x9e, 0x57, 0x76, 0xd0, 0x80, 0xc9,
	0xc4, 0x99, 0x11, 0xf1, 0x01, 0x7c, 0x6f, 0xc9, 0x26, 0x81, 0x46, 0xec, 0xa5, 0xb7, 0x99, 0xe1,
	0x9f, 0x6f, 0xe7, 0x63, 0x01, 0x2a, 0xf2, 0xb8, 0xa8, 0x99, 0x94, 0x4c, 0xdc, 0xd4, 0xf9, 0x12,
	0x26, 0x2b, 0xfc, 0x5a, 0x91, 0x47, 0x8b, 0x1f, 0x9f, 0x28, 0x6a, 0x52, 0x18, 0x3b, 0xef, 0x19,
	0x45, 0xd2, 0x28, 0x8b, 0xe6, 0xfb, 0xb6, 0x6f, 0x4d, 0x06, 0x07, 0x85, 0xdc, 0x10, 0xa9, 0x28,
	0xbb, 0x3a, 0x1d, 0x65, 0xd1, 0x7c, 0xcf, 0xae, 0x8f, 0xf2, 0x53, 0x98, 0x3e, 0xaa, 0x63, 0x5d,
	0x16, 0xa2, 0x58, 0x21, 0xf7, 0x4c, 0x03, 0x71, 0x4d, 0xac, 0x01, 0x98, 0xd8, 0x50, 0xe7, 0x27,
	0x90, 0x3c, 0x60, 0x49, 0xfc, 0xbd, 0x1e, 0x72, 0xfa, 0xd6, 0xbd, 0x1a, 0xea, 0xfc, 0x0c, 0x0e,
	0xef, 0x1b, 0x90, 0x7b, 0xb7, 0x28, 0x35, 0x55, 0x82, 0xcd, 0x7d, 0x25, 0x8a, 0xb8, 0x57, 0xec,
	0xef, 0xeb, 0xda, 0xf3, 0x9f, 0x11, 0xc4, 0x8d, 0x89, 0xb9, 0x84, 0x71, 0x27, 0x65, 0xa6, 0x8b,
	0xa0, 0x3c, 0x74, 0x9c, 0x1d, 0xb7, 0xd3, 0x3f, 0xe8, 0x7c, 0xc7, 0xdc, 0x42, 0x32, 0x10, 0x30,
	0xb3, 0x36, 0xf9, 0x9f, 0xd5, 0x66, 0xca, 0x35, 0x4c, 0x2c, 0x3a, 0x7f, 0xc7, 0x54, 0xb6, 0x8a,
	0xe6, 0xa8, 0x8d, 0x0e, 0x84, 0x37, 0xef, 0x5f, 0x41, 0xf2, 0xcc, 0x85, 0xe2, 0x13, 0x6d, 0xb3,
	0xfe, 0xb2, 0x1b, 0x3e, 0xf8, 0xe2, 0x37, 0x00, 0x00, 0xff, 0xff, 0x43, 0xfa, 0x7f, 0x9a, 0xee,
	0x01, 0x00, 0x00,
}
