// Code generated by protoc-gen-go. DO NOT EDIT.
// source: node.proto

package node

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GeneralRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	IsBootstrap          bool     `protobuf:"varint,2,opt,name=isBootstrap,proto3" json:"isBootstrap,omitempty"`
	Port                 uint32   `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Path                 string   `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GeneralRequest) Reset()         { *m = GeneralRequest{} }
func (m *GeneralRequest) String() string { return proto.CompactTextString(m) }
func (*GeneralRequest) ProtoMessage()    {}
func (*GeneralRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{0}
}

func (m *GeneralRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeneralRequest.Unmarshal(m, b)
}
func (m *GeneralRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeneralRequest.Marshal(b, m, deterministic)
}
func (m *GeneralRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeneralRequest.Merge(m, src)
}
func (m *GeneralRequest) XXX_Size() int {
	return xxx_messageInfo_GeneralRequest.Size(m)
}
func (m *GeneralRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GeneralRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GeneralRequest proto.InternalMessageInfo

func (m *GeneralRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *GeneralRequest) GetIsBootstrap() bool {
	if m != nil {
		return m.IsBootstrap
	}
	return false
}

func (m *GeneralRequest) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *GeneralRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type GeneralResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GeneralResponse) Reset()         { *m = GeneralResponse{} }
func (m *GeneralResponse) String() string { return proto.CompactTextString(m) }
func (*GeneralResponse) ProtoMessage()    {}
func (*GeneralResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{1}
}

func (m *GeneralResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeneralResponse.Unmarshal(m, b)
}
func (m *GeneralResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeneralResponse.Marshal(b, m, deterministic)
}
func (m *GeneralResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeneralResponse.Merge(m, src)
}
func (m *GeneralResponse) XXX_Size() int {
	return xxx_messageInfo_GeneralResponse.Size(m)
}
func (m *GeneralResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GeneralResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GeneralResponse proto.InternalMessageInfo

func (m *GeneralResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*GeneralRequest)(nil), "node.GeneralRequest")
	proto.RegisterType((*GeneralResponse)(nil), "node.GeneralResponse")
}

func init() { proto.RegisterFile("node.proto", fileDescriptor_0c843d59d2d938e7) }

var fileDescriptor_0c843d59d2d938e7 = []byte{
	// 240 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0xb1, 0x4a, 0x04, 0x41,
	0x0c, 0x86, 0xdd, 0x73, 0x71, 0x35, 0x72, 0x27, 0x0c, 0x0a, 0x83, 0xd5, 0xb0, 0xd5, 0x82, 0x70,
	0x85, 0x36, 0x57, 0x29, 0x58, 0x68, 0x73, 0x5e, 0x31, 0x0a, 0xd6, 0x23, 0x13, 0xce, 0x05, 0x77,
	0x33, 0x26, 0x11, 0xf1, 0xd9, 0x7c, 0x39, 0xd9, 0xd1, 0x13, 0xb5, 0x73, 0xbb, 0x2f, 0xff, 0x90,
	0x7c, 0x19, 0x02, 0xd0, 0x53, 0xc4, 0x79, 0x62, 0x52, 0x32, 0xe5, 0xc0, 0xb5, 0xc2, 0xec, 0x1a,
	0x7b, 0xe4, 0xf0, 0xe4, 0xf1, 0xf9, 0x05, 0x45, 0x8d, 0x85, 0x2a, 0xc4, 0xc8, 0x28, 0x62, 0x0b,
	0x57, 0x34, 0x7b, 0x7e, 0x53, 0x1a, 0x07, 0xfb, 0xad, 0x5c, 0x12, 0xa9, 0x28, 0x87, 0x64, 0x27,
	0xae, 0x68, 0x76, 0xfd, 0xcf, 0xc8, 0x18, 0x28, 0x13, 0xb1, 0xda, 0x6d, 0x57, 0x34, 0x53, 0x9f,
	0x39, 0x67, 0x41, 0x1f, 0x6d, 0x99, 0x87, 0x65, 0xae, 0x4f, 0xe0, 0xe0, 0xdb, 0x2a, 0x89, 0x7a,
	0xc1, 0x41, 0xdb, 0xa1, 0x48, 0x58, 0xe3, 0x46, 0xfb, 0x55, 0x9e, 0xbe, 0x4f, 0xa0, 0x5c, 0x51,
	0x44, 0xb3, 0x80, 0x6a, 0x85, 0xaf, 0x19, 0x0f, 0xe7, 0xf9, 0x27, 0xbf, 0x57, 0x3f, 0x3e, 0xfa,
	0x93, 0x7e, 0x8e, 0xae, 0xb7, 0xcc, 0x39, 0x4c, 0x6f, 0x35, 0xb0, 0x2e, 0x5b, 0xd1, 0xe1, 0xf1,
	0xbf, 0xfd, 0x0b, 0xa8, 0x96, 0xb4, 0x1e, 0x63, 0xbe, 0x80, 0x99, 0xc7, 0x10, 0xaf, 0x98, 0xba,
	0x1b, 0xec, 0x88, 0xdf, 0x46, 0xac, 0x7e, 0xcf, 0xad, 0xe2, 0x1d, 0x8d, 0xea, 0x7f, 0xd8, 0xc9,
	0xd7, 0x3e, 0xfb, 0x08, 0x00, 0x00, 0xff, 0xff, 0x01, 0x88, 0x15, 0x40, 0xfb, 0x01, 0x00, 0x00,
}
