// Code generated by protoc-gen-go. DO NOT EDIT.
// source: shard.proto

package shard

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GeneralRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Addresses            []string `protobuf:"bytes,2,rep,name=addresses,proto3" json:"addresses,omitempty"`
	IsBootstrap          bool     `protobuf:"varint,3,opt,name=isBootstrap,proto3" json:"isBootstrap,omitempty"`
	Port                 uint32   `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	Exponent             uint32   `protobuf:"varint,5,opt,name=exponent,proto3" json:"exponent,omitempty"`
	Path                 string   `protobuf:"bytes,6,opt,name=path,proto3" json:"path,omitempty"`
	Bytes                []byte   `protobuf:"bytes,7,opt,name=bytes,proto3" json:"bytes,omitempty"`
	NetworkName          string   `protobuf:"bytes,8,opt,name=networkName,proto3" json:"networkName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GeneralRequest) Reset()         { *m = GeneralRequest{} }
func (m *GeneralRequest) String() string { return proto.CompactTextString(m) }
func (*GeneralRequest) ProtoMessage()    {}
func (*GeneralRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_319ea41e44cdc364, []int{0}
}

func (m *GeneralRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeneralRequest.Unmarshal(m, b)
}
func (m *GeneralRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeneralRequest.Marshal(b, m, deterministic)
}
func (m *GeneralRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeneralRequest.Merge(m, src)
}
func (m *GeneralRequest) XXX_Size() int {
	return xxx_messageInfo_GeneralRequest.Size(m)
}
func (m *GeneralRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GeneralRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GeneralRequest proto.InternalMessageInfo

func (m *GeneralRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *GeneralRequest) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func (m *GeneralRequest) GetIsBootstrap() bool {
	if m != nil {
		return m.IsBootstrap
	}
	return false
}

func (m *GeneralRequest) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *GeneralRequest) GetExponent() uint32 {
	if m != nil {
		return m.Exponent
	}
	return 0
}

func (m *GeneralRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *GeneralRequest) GetBytes() []byte {
	if m != nil {
		return m.Bytes
	}
	return nil
}

func (m *GeneralRequest) GetNetworkName() string {
	if m != nil {
		return m.NetworkName
	}
	return ""
}

type GeneralResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GeneralResponse) Reset()         { *m = GeneralResponse{} }
func (m *GeneralResponse) String() string { return proto.CompactTextString(m) }
func (*GeneralResponse) ProtoMessage()    {}
func (*GeneralResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_319ea41e44cdc364, []int{1}
}

func (m *GeneralResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeneralResponse.Unmarshal(m, b)
}
func (m *GeneralResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeneralResponse.Marshal(b, m, deterministic)
}
func (m *GeneralResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeneralResponse.Merge(m, src)
}
func (m *GeneralResponse) XXX_Size() int {
	return xxx_messageInfo_GeneralResponse.Size(m)
}
func (m *GeneralResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GeneralResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GeneralResponse proto.InternalMessageInfo

func (m *GeneralResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*GeneralRequest)(nil), "shard.GeneralRequest")
	proto.RegisterType((*GeneralResponse)(nil), "shard.GeneralResponse")
}

func init() { proto.RegisterFile("shard.proto", fileDescriptor_319ea41e44cdc364) }

var fileDescriptor_319ea41e44cdc364 = []byte{
	// 322 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0x4d, 0x4f, 0xc2, 0x40,
	0x10, 0xb5, 0x42, 0xa1, 0x0c, 0x2a, 0x71, 0xa3, 0x66, 0x43, 0x3c, 0x34, 0x9c, 0x9a, 0x98, 0x70,
	0xd0, 0x8b, 0x09, 0x27, 0xf1, 0xeb, 0xa2, 0x24, 0xac, 0x07, 0xcf, 0x0b, 0x9d, 0x00, 0x11, 0xba,
	0x75, 0x67, 0x1a, 0xe4, 0x7f, 0xf8, 0x1b, 0xfd, 0x1d, 0x86, 0x2d, 0x45, 0xf4, 0x56, 0x6f, 0xef,
	0xbd, 0x74, 0x5e, 0xe7, 0xbd, 0x59, 0x68, 0xd2, 0x54, 0xdb, 0xb8, 0x9b, 0x5a, 0xc3, 0x46, 0xf8,
	0x8e, 0x74, 0xbe, 0x3c, 0x38, 0x7a, 0xc4, 0x04, 0xad, 0x9e, 0x2b, 0x7c, 0xcf, 0x90, 0x58, 0x48,
	0xa8, 0xeb, 0x38, 0xb6, 0x48, 0x24, 0xbd, 0xd0, 0x8b, 0x1a, 0xaa, 0xa0, 0xe2, 0x1c, 0x1a, 0x1b,
	0x88, 0x24, 0xf7, 0xc3, 0x4a, 0xd4, 0x50, 0x3f, 0x82, 0x08, 0xa1, 0x39, 0xa3, 0xbe, 0x31, 0x4c,
	0x6c, 0x75, 0x2a, 0x2b, 0xa1, 0x17, 0x05, 0x6a, 0x57, 0x12, 0x02, 0xaa, 0xa9, 0xb1, 0x2c, 0xab,
	0xa1, 0x17, 0x1d, 0x2a, 0x87, 0x45, 0x1b, 0x02, 0xfc, 0x48, 0x4d, 0x82, 0x09, 0x4b, 0xdf, 0xe9,
	0x5b, 0xee, 0xbe, 0xd7, 0x3c, 0x95, 0x35, 0xb7, 0x86, 0xc3, 0xe2, 0x04, 0xfc, 0xd1, 0x8a, 0x91,
	0x64, 0x3d, 0xf4, 0xa2, 0x03, 0x95, 0x93, 0xf5, 0xbf, 0x13, 0xe4, 0xa5, 0xb1, 0x6f, 0x03, 0xbd,
	0x40, 0x19, 0xb8, 0x81, 0x5d, 0xa9, 0x73, 0x01, 0xad, 0x6d, 0x4e, 0x4a, 0x4d, 0x42, 0xb8, 0x0e,
	0xba, 0x40, 0x22, 0x3d, 0xc1, 0x22, 0xe8, 0x86, 0x5e, 0x7e, 0x56, 0xc0, 0x7f, 0x59, 0xf7, 0x23,
	0x7a, 0x10, 0x0c, 0x70, 0x99, 0xe3, 0xd3, 0x6e, 0x5e, 0xe0, 0xef, 0xbe, 0xda, 0x67, 0x7f, 0xe5,
	0xdc, 0xbe, 0xb3, 0x27, 0xee, 0xe0, 0xb8, 0x18, 0x7e, 0x9d, 0xf1, 0x74, 0x60, 0x62, 0xa4, 0xf2,
	0x2e, 0xd7, 0xc5, 0x2e, 0xa5, 0x27, 0xfb, 0xd0, 0x1a, 0x66, 0x68, 0x57, 0x0f, 0xc6, 0xde, 0x6c,
	0x4e, 0x58, 0xda, 0xa3, 0x07, 0xc1, 0x93, 0x99, 0xfc, 0x73, 0x81, 0x67, 0x68, 0xdf, 0xea, 0xf9,
	0x38, 0x9b, 0x6b, 0xc6, 0x61, 0xa6, 0x63, 0xab, 0x79, 0x36, 0xbe, 0x2f, 0xce, 0x5b, 0xd6, 0x6e,
	0x54, 0x73, 0x4f, 0xf7, 0xea, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xb4, 0x09, 0x8e, 0xd1, 0xc9, 0x02,
	0x00, 0x00,
}
