// Code generated by protoc-gen-go. DO NOT EDIT.
// source: database.proto

package database

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GeneralRequest struct {
	DataPath             string   `protobuf:"bytes,1,opt,name=dataPath,proto3" json:"dataPath,omitempty"`
	NetworkName          string   `protobuf:"bytes,2,opt,name=networkName,proto3" json:"networkName,omitempty"`
	NetworkID            uint32   `protobuf:"varint,3,opt,name=networkID,proto3" json:"networkID,omitempty"`
	AcceptableTimeout    uint32   `protobuf:"varint,4,opt,name=acceptableTimeout,proto3" json:"acceptableTimeout,omitempty"`
	Address              string   `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	ByteVal              []byte   `protobuf:"bytes,6,opt,name=byteVal,proto3" json:"byteVal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GeneralRequest) Reset()         { *m = GeneralRequest{} }
func (m *GeneralRequest) String() string { return proto.CompactTextString(m) }
func (*GeneralRequest) ProtoMessage()    {}
func (*GeneralRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b90fe3356ea5df07, []int{0}
}

func (m *GeneralRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeneralRequest.Unmarshal(m, b)
}
func (m *GeneralRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeneralRequest.Marshal(b, m, deterministic)
}
func (m *GeneralRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeneralRequest.Merge(m, src)
}
func (m *GeneralRequest) XXX_Size() int {
	return xxx_messageInfo_GeneralRequest.Size(m)
}
func (m *GeneralRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GeneralRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GeneralRequest proto.InternalMessageInfo

func (m *GeneralRequest) GetDataPath() string {
	if m != nil {
		return m.DataPath
	}
	return ""
}

func (m *GeneralRequest) GetNetworkName() string {
	if m != nil {
		return m.NetworkName
	}
	return ""
}

func (m *GeneralRequest) GetNetworkID() uint32 {
	if m != nil {
		return m.NetworkID
	}
	return 0
}

func (m *GeneralRequest) GetAcceptableTimeout() uint32 {
	if m != nil {
		return m.AcceptableTimeout
	}
	return 0
}

func (m *GeneralRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *GeneralRequest) GetByteVal() []byte {
	if m != nil {
		return m.ByteVal
	}
	return nil
}

type GeneralResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GeneralResponse) Reset()         { *m = GeneralResponse{} }
func (m *GeneralResponse) String() string { return proto.CompactTextString(m) }
func (*GeneralResponse) ProtoMessage()    {}
func (*GeneralResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b90fe3356ea5df07, []int{1}
}

func (m *GeneralResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeneralResponse.Unmarshal(m, b)
}
func (m *GeneralResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeneralResponse.Marshal(b, m, deterministic)
}
func (m *GeneralResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeneralResponse.Merge(m, src)
}
func (m *GeneralResponse) XXX_Size() int {
	return xxx_messageInfo_GeneralResponse.Size(m)
}
func (m *GeneralResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GeneralResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GeneralResponse proto.InternalMessageInfo

func (m *GeneralResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*GeneralRequest)(nil), "database.GeneralRequest")
	proto.RegisterType((*GeneralResponse)(nil), "database.GeneralResponse")
}

func init() { proto.RegisterFile("database.proto", fileDescriptor_b90fe3356ea5df07) }

var fileDescriptor_b90fe3356ea5df07 = []byte{
	// 311 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0x4f, 0x4f, 0xf2, 0x40,
	0x10, 0xc6, 0xdf, 0xbe, 0x28, 0x7f, 0x06, 0x81, 0xb8, 0xa7, 0x95, 0x78, 0x68, 0x38, 0x91, 0x68,
	0x38, 0xe8, 0x17, 0x10, 0x24, 0xa0, 0x07, 0x89, 0x6e, 0x88, 0x9e, 0xa7, 0xec, 0x44, 0x89, 0x6c,
	0xb7, 0xee, 0x6e, 0x25, 0xfd, 0x92, 0x7e, 0x1c, 0xcf, 0xa6, 0xb5, 0xad, 0x1a, 0x3d, 0x95, 0xe3,
	0x6f, 0x9f, 0xc9, 0x6f, 0x32, 0x4f, 0xb2, 0xd0, 0x95, 0xe8, 0x30, 0x40, 0x4b, 0xa3, 0xc8, 0x68,
	0xa7, 0x59, 0xb3, 0xe0, 0xc1, 0x9b, 0x07, 0xdd, 0x39, 0x85, 0x64, 0x70, 0x23, 0xe8, 0x25, 0x26,
	0xeb, 0x58, 0x1f, 0xb2, 0xf8, 0x16, 0xdd, 0x13, 0xf7, 0x7c, 0x6f, 0xd8, 0x12, 0x25, 0x33, 0x1f,
	0xda, 0x21, 0xb9, 0xad, 0x36, 0xcf, 0x0b, 0x54, 0xc4, 0xff, 0x67, 0xf1, 0xf7, 0x27, 0x76, 0x0c,
	0xad, 0x1c, 0xaf, 0xa7, 0xbc, 0xe6, 0x7b, 0xc3, 0x8e, 0xf8, 0x7a, 0x60, 0xa7, 0x70, 0x88, 0xab,
	0x15, 0x45, 0x0e, 0x83, 0x0d, 0x2d, 0xd7, 0x8a, 0x74, 0xec, 0xf8, 0x5e, 0x36, 0xf5, 0x3b, 0x60,
	0x1c, 0x1a, 0x28, 0xa5, 0x21, 0x6b, 0xf9, 0x7e, 0xb6, 0xa9, 0xc0, 0x34, 0x09, 0x12, 0x47, 0xf7,
	0xb8, 0xe1, 0x75, 0xdf, 0x1b, 0x1e, 0x88, 0x02, 0x07, 0x27, 0xd0, 0x2b, 0xef, 0xb1, 0x91, 0x0e,
	0x2d, 0xa5, 0xc3, 0x8a, 0xac, 0xc5, 0x47, 0xca, 0xef, 0x29, 0xf0, 0xec, 0xbd, 0x06, 0xcd, 0x69,
	0x5e, 0x05, 0x9b, 0x42, 0x7b, 0x41, 0xdb, 0x12, 0xf9, 0xa8, 0x2c, 0xed, 0x67, 0x41, 0xfd, 0xa3,
	0x3f, 0x92, 0xcf, 0x55, 0x83, 0x7f, 0xec, 0x02, 0x1a, 0x63, 0x29, 0x17, 0x5a, 0x56, 0x36, 0x5c,
	0x02, 0x08, 0x52, 0xfa, 0x95, 0x76, 0x91, 0x5c, 0x41, 0xef, 0x2e, 0x26, 0x93, 0xcc, 0xb4, 0x19,
	0x17, 0x9d, 0x55, 0x33, 0xcd, 0xa0, 0xf3, 0x60, 0xd6, 0x8e, 0x96, 0xfa, 0x86, 0x94, 0x36, 0x49,
	0x55, 0xcf, 0x1c, 0xba, 0x82, 0x50, 0xce, 0x8c, 0x56, 0xbb, 0x89, 0x26, 0xd0, 0x4a, 0x25, 0x93,
	0xc4, 0x51, 0xd5, 0xa3, 0x82, 0x7a, 0xf6, 0x0f, 0xce, 0x3f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xaf,
	0x63, 0x8d, 0x1d, 0x19, 0x03, 0x00, 0x00,
}
